### PR TITLE
Add Archer USB T3U Plus

### PR DESCRIPTION
**Pull request by jmajnert**
Add Archer USB T3U Plus product and vendor ids.

### CODE REVIEW

**Comment by jmajnert** [comment]
The driver seems to be working OK with my Archer USB T3U Plus device (TP-Link AC1300) on Ubuntu 18.04.4 LTS, 4.15.0-91-generic.

**Comment by foarsitter** [comment]
Tried to install the driver with your version on a clean install of Ubuntu 18.04 (5.3.0-28-generic) and 20.04 (5.4.0-29-generic and 5.4.0-26-generic). Without of luck. 

dmesg dump[20.04](https://pastebin.com/zQf1s0Uj) [18.04](https://pastebin.com/pTc6jDjV)

```
#To run script, type 'sudo ./install_t3u.sh' in ~/Downloads/
##This bash-script assumes your CPU has eight-threads.

# sudo apt-get install linux-headers-generic build-essential
# sudo apt install git dkms -y

sudo dkms remove rtl88x2bu/5.3.1 --all;
sudo dkms remove 8822bu/1.1 --all;

git clone https://github.com/jmajnert/rtl8822bu.git;
cd rtl8822bu/;
make uninstall -j 4;
make -j 8;
make install -j 4;
cd ../;
sudo cp -R rtl8822bu/ /usr/src/.-rtl8822bu/;
sudo dkms add ./rtl8822bu;
sudo rm -R rtl8822bu/;
echo "Install completed. Please reboot.";
echo "Try: 'sudo shutdown -f now' or 'reboot'";
```

**Comment by razvanphp** [comment]
For Nvidia Jetson Nano and Xavier, this works with `ARCH=arm64 make -j 4` because of the `aarch64` architecture.

**Comment by fgsalomon** [comment]
> Tried to install the driver with your version on a clean install of Ubuntu 18.04 (5.3.0-28-generic) and 20.04 (5.4.0-29-generic and 5.4.0-26-generic). Without of luck.
> 
> dmesg dump[20.04](https://pastebin.com/zQf1s0Uj) [18.04](https://pastebin.com/pTc6jDjV)
> 
> ```
> #To run script, type 'sudo ./install_t3u.sh' in ~/Downloads/
> ##This bash-script assumes your CPU has eight-threads.
> 
> # sudo apt-get install linux-headers-generic build-essential
> # sudo apt install git dkms -y
> 
> sudo dkms remove rtl88x2bu/5.3.1 --all;
> sudo dkms remove 8822bu/1.1 --all;
> 
> git clone https://github.com/jmajnert/rtl8822bu.git;
> cd rtl8822bu/;
> make uninstall -j 4;
> make -j 8;
> make install -j 4;
> cd ../;
> sudo cp -R rtl8822bu/ /usr/src/.-rtl8822bu/;
> sudo dkms add ./rtl8822bu;
> sudo rm -R rtl8822bu/;
> echo "Install completed. Please reboot.";
> echo "Try: 'sudo shutdown -f now' or 'reboot'";
> ```

This script works me on Ubuntu 18.04.4 (4.15.0-111-generic) but it doesn't with next kernel version (4.15.0-112-generic).

**Comment by jabss** [comment]
Hi,

Can you put the NIC into Monitor mode?
I'm using the EntropicEffect:master clone I'm unable to...

```

sudo iw --debug wlan0 set monitor control

-- Debug: Sent Message:
--------------------------   BEGIN NETLINK MESSAGE ---------------------------
  [NETLINK HEADER] 16 octets
    .nlmsg_len = 44
    .type = 29 <0x1d>
    .flags = 5 <REQUEST,ACK>
    .seq = 1619047673
    .port = 452986045
  [GENERIC NETLINK HEADER] 4 octets
    .cmd = 6
    .version = 0
    .unused = 0
  [PAYLOAD] 24 octets
    08 00 03 00 03 00 00 00 08 00 05 00 06 00 00 00 ................
    08 00 17 00 04 00 03 00                         ........
---------------------------  END NETLINK MESSAGE   ---------------------------
-- Debug: Received Message:
--------------------------   BEGIN NETLINK MESSAGE ---------------------------
  [NETLINK HEADER] 16 octets
    .nlmsg_len = 64
    .type = 2 <ERROR>
    .flags = 0 <>
    .seq = 1619047673
    .port = 452986045
  [ERRORMSG] 20 octets
    .error = -95 "Operation not supported"
  [ORIGINAL MESSAGE] 16 octets
    .nlmsg_len = 16
    .type = 29 <0x1d>
    .flags = 5 <REQUEST,ACK>
    .seq = 1619047673
    .port = 452986045
---------------------------  END NETLINK MESSAGE   ---------------------------
command failed: Operation not supported (-95)
```


 

Any idea why?

 

```
└─$ uname -a                                                                                                    161 ⨯
Linux kali 5.10.0-kali7-amd64 #1 SMP Debian 5.10.28-1kali1 (2021-04-12) x86_64 GNU/Linux

└─$ lsusb                                                                                                       161 ⨯
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 002: ID 2357:0115 TP-Link Archer T4U ver.3
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

```

Thanks in advance

**Pull request closed without merging**
